# Generated by Django 5.1.6 on 2025-02-24 00:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("uid", models.CharField(max_length=20, unique=True)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=100)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, upload_to="user/profile_picture/%Y/%m/%d/"
                    ),
                ),
                (
                    "profile_cover",
                    models.ImageField(
                        blank=True, upload_to="user/cover_picture/%Y/%m/%d/"
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
