# Generated by Django 5.1.6 on 2025-02-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_userprofile_id_alter_userprofile_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
