apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        image: ${REGISTRY_NAME}/${AUTH_IMAGE}:${APP_VERSION}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "700m"
        envFrom:
        - secretRef:
            name: env-secret
        - configMapRef:
            name: auth-env
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth-server
  ports:
  - port: 9000
    targetPort: 9000






