apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: ${REGISTRY_NAME}/${GATEWAY_IMAGE}:${APP_VERSION}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "700m"
        envFrom:
        - secretRef:
            name: env-secret
        - configMapRef:
            name: gateway-env
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
  - port: 8888
    targetPort: 8888
