// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"hhub/connection-service/internal/controllers"
	"hhub/connection-service/internal/repositories/follow"
	"hhub/connection-service/internal/repositories/friend"
	"hhub/connection-service/internal/services/follow"
	"hhub/connection-service/internal/services/friend"
)

// Injectors from follow_wire.go:

func InitFollowController() (*controllers.FollowController, error) {
	iFollowRepository := repositories_follow.NewFollowRepository()
	iFollowService := services_follow.NewFollowService(iFollowRepository)
	followController := controllers.NewFollowController(iFollowService)
	return followController, nil
}

// Injectors from friend_wire.go:

func InitFriendController() (*controllers.FriendController, error) {
	iFriendRepository := repositories_friend.NewFriendRepository()
	iFollowRepository := repositories_follow.NewFollowRepository()
	iFollowService := services_follow.NewFollowService(iFollowRepository)
	iFriendService := services_friend.NewFriendService(iFriendRepository, iFollowService)
	friendController := controllers.NewFriendController(iFriendService)
	return friendController, nil
}
