apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.7.0
          # resources:
          #   limits:
          #     memory: "600Mi"
          #     cpu: "1000m"
          ports:
            - containerPort: 9092
            - containerPort: 9094
          envFrom:
            - configMapRef:
                name: kafka-env
---

apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
    name: internal
  - protocol: TCP
    port: 9094
    targetPort: 9094
    name: external