server:
  port: 8080

spring:
  application:
    name: identity-service
  datasource:
    url: ${IDENTITY_DB_URL}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: ${EXPIRY_TIME} # in seconds
  refreshable-duration: ${REFRESH_DURATION} # in seconds

app:
  services:
    profile: http://132.12.0.10:8000/profiles