server:
  debug: false
  port: 8224
  # prefix: "/api/v1"
  prefix:
mysql:
  host: 127.0.0.1
  port: 3386
  user: root
  password: 123A123
  database: test_connection_service
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
auth:
  url: http://localhost:9000
  client: test-client
  secret: secret
redis:
  address: :6339
  password: testpass

# keycloak:
#   url: http://127.0.0.1:8181
#   realm: test-realm-v0.1
#   client: test-internal-client
#   secret: EJ9rEFAgBiSiACWP636lWWvlHpCkThMX