server:
  debug: false
  port: 8224
  prefix: "/api/v1"
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: "@123456"
  database: test_connection_service
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
