server:
  debug: true
  port: 8224
  # prefix: "/api/v1"
  prefix:
mysql:
  host: mysqldb
  port: 3386
  user: root
  password: 123A123
  database: test_connection_service
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
auth:
  url: http://auth:900
  client: test-client
  secret: secret

# keycloak:
#   url: http://idp-keycloak:8080
#   realm: test-realm-v0.1
#   client: test-internal-client
#   secret: "**********"